# -*- coding: utf-8 -*-
"""setup_logging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TD9DfNPCUYoJoQsks58Xklt-ZGRp_7A4
"""

import os
import time
from datetime import datetime
import logging

def setup_logging(base_path, model, rep_dim):
    timestamp = time.time()
    value = datetime.fromtimestamp(timestamp)
    timestring = value.strftime('%b-%d %H:%M')
    filename = '{} {}-dim {}'.format(model, rep_dim, timestring)
    log_file = os.path.join(os.path.join(base_path, 'logs'), filename)

    # Set up logging
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    file_handler = logging.FileHandler(log_file + '.txt')
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)
    
    return filename