# -*- coding: utf-8 -*-
"""unzip_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13KAJg2jn7EYw5tjbxfYD9TH-hmQ8wnMq
"""

def unzip_data(base_path):
    import os
    import tarfile
    
    data_path = os.path.join(base_path, 'data/')
    #print('base path : ', base_path)
    #print('data path : ', data_path)
    
    if not os.path.isfile(os.path.join(data_path, 'clean_images.tar.gz')):
        raise FileNotFoundError('clean_images.tar.gz not found in data/')
    
    tar = tarfile.open(os.path.join(data_path, 'clean_images.tar.gz'))
    tar.extractall(path=data_path)
    tar.close()