# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lvk2haInJAJhESzp9kYEpdCv0abW-C1I
"""

from .VGG import VGG
from .ResNet import resnet18, resnet34, resnet50, resnet101

def get_model(model='vgg', kind='autoencoder', rep_dim=490):
    model = model.lower()
    models = {
        'vgg': VGG(kind=kind, rep_dim=rep_dim),
        'resnet18': resnet18(kind=kind, rep_dim=rep_dim),
        'resnet34': resnet34(kind=kind, rep_dim=rep_dim),
        'resnet50': resnet50(kind=kind, rep_dim=rep_dim),
        'resnet101': resnet101(kind=kind, rep_dim=rep_dim)
    }
    
    try:
        assert model in models.keys()
    except:
        raise ValueError('{} not implemented.'.format(model))
        
    
    return models[model]
    
    return

